github: [jalilkartal]                       # Replace with your GitHub Sponsors username if you enable it
patreon: kartalol                        # Your Patreon username
open_collective: kartalol       # Open Collective project name
ko_fi: kartalol                          # Ko-fi username
tidelift:                                   # Leave blank if not applicable
community_bridge:                           # Leave blank or add project name if using
liberapay: kartalol                      # Liberapay username
issuehunt: kartalol                      # IssueHunt username
lfx_crowdfunding:                           # Leave blank or add your LFX project name
polar: kartalol                          # Polar.sh username (if applicable)
buy_me_a_coffee: kartalol                # Buy Me a Coffee username
thanks_dev: kartalol                     # thanks.dev username
custom:
  - https://opencollective.com/kartalol
  - https://ko-fi.com/kartalol
  - https://www.patreon.com/kartalol
  - https://buymeacoffee.com/kartalol
